trigger:
  branches:
    exclude:
      - "*"

pr:
  autoCancel: true
  branches:
    include:
      - "*"

stages:
  - template: code_quality_checks.yml
  - stage: "Create package and test"
    displayName: "Python tests"

    jobs:
      - job: "linux"
        displayName: "Build package and test"
        timeoutInMinutes: 20
        pool:
          vmImage: "ubuntu-18.04"
        steps:
          - checkout: self
            submodules: true
          - bash: echo "##vso[task.prependpath]$CONDA/bin"
            displayName: "Configure Conda directories"
          - bash: |
              set -ex
              conda --version
              conda install --yes anaconda-client conda-build
              conda config --set always_yes yes --set changeps1 no
            displayName: "conda configuration"
          - bash: |
              conda build --channel conda-forge --channel scipp ./conda
            displayName: "Conda Build"
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(conda_dir)/conda-bld/linux-64'
              ArtifactName: 'linux-64'
            displayName: "Publish Conda package artefacts"
