package:
  name: scippwidgets
  version: {{GIT_DESCRIBE_TAG}}

source:
  path: ..

requirements:
  build:
    - sphinx>=1.6
    - sphinx_rtd_theme
  run:
    - scipp
    - ipywidgets
    - matplotlib
    - ipyfilechooser

test:
  import:
    - scippwidgets
    - scippwidgets.inputs
    - scippwidgets.validators
    - scippwidgets.widgets
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - python -m pytest -v

build:
  number: {{environ.get('GIT_DESCRIBE_NUMBER', 0)}}
  noarch: python
  script:
    - python setup.py install

about:
  home: https://github.com/scipp/scippwidgets
  license: BSD-3-Clause
  summary: ipywidget wrappers for scipp
  description: ipywidget wrappers for scipp
  dev_url: https://github.com/scipp/scippwidgets
  doc_url: https://scipp.github.io/scippwidgets
